---
title: "Homework Dataset"
author: "Lauren Middleton"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries

```{r}
library(nhanesA)
library(tidyverse)
library(sjlabelled)
library(here)
```


# Download data from 2013-2014 cycle

```{r}

# Download demographic data
demog <- nhanes("DEMO_H")

# Download cognitive data
cog <- nhanes("CFQ_H")

# Download cotinine data
cotinine <- nhanes("COT_H")

# Download lead and cadmium data
metals <- nhanes("PBCD_H")
```


# Keep useful variables

```{r}

demog_clean <- demog %>%
  select(SEQN,
         RIAGENDR,
         RIDAGEYR,
         RIDRETH1,
         INDFMPIR,
         DMDEDUC2,
         SDMVSTRA,
         SDMVPSU
         ) %>%
  remove_label(SEQN)

cog_clean <- cog %>%
  select(SEQN,
         CFDDS) %>%
  remove_label(SEQN)

cotinine_clean <- cotinine %>%
  select(SEQN,
         LBXCOT) %>%
  remove_label(SEQN)

metals_clean <- metals %>%
  select(SEQN,
         LBXBPB,
         LBXBCD) %>%
  remove_label(SEQN)
```


# Merge datasets

```{r}

# Merge four datasets
nhanes_merge <- left_join(demog_clean, cog_clean, by = "SEQN") %>%
  left_join(., cotinine_clean, by = "SEQN") %>%
  left_join(., metals_clean, by = "SEQN")


dim(nhanes_merge)
#698  12
```


# Clean dataset

```{r}

# Calculate MCI cutoff based on: https://www.sciencedirect.com/science/article/pii/S0160412014003250?via%3Dihub
summary(nhanes_merge$CFDDS)
#25th percentile is 33, min=5, median=46, max=93

# Subset age, label values, set references, create MCI variable, reorder variables
nhanes_clean <- nhanes_merge %>%
  filter(RIDAGEYR >= 60) %>%
  mutate(race_eth = case_when(RIDRETH1 == 1 ~ "Mexican American",
                              RIDRETH1 == 2 ~ "Other Hispanic",
                              RIDRETH1 == 3 ~ "Non-Hispanic White",
                              RIDRETH1 == 4 ~ "Non-Hispanic Black",
                              RIDRETH1 == 5 ~ "Other Race"),
         sex = case_when(RIAGENDR == 1 ~ "Male",
                         RIAGENDR == 2 ~ "Female")) %>%
  mutate(education = case_when(DMDEDUC2 == 1 | DMDEDUC2 == 2 ~ "Less than high school",
                               DMDEDUC2 == 3 ~ "High school or GED",
                               DMDEDUC2 == 4 | DMDEDUC2 == 5 ~ "More than high school",
                               DMDEDUC2 == 7 | DMDEDUC2 == 9 ~ "Unknown"),
         education = na_if(education, "Unknown")) %>% #no missings
  mutate(sex = relevel(factor(sex),
                       ref = "Male"),
         race_eth = relevel(factor(race_eth),
                            ref = "Non-Hispanic White"),
         education = relevel(factor(education,
                                    levels = c("Less than high school",
                                               "High school or GED",
                                               "More than high school")),
                             ref = "Less than high school")) %>%
  mutate(MCI = case_when(CFDDS > 33 ~ "No Impairment",
                         CFDDS <= 33 ~ "Mild Cognitive Impairment"),
         MCI = relevel(factor(MCI),
                       ref = "No Impairment")) %>%
  relocate(race_eth, .after = RIDRETH1) %>%
  relocate(sex, .after = RIAGENDR) %>%
  relocate(education, .after = DMDEDUC2) %>%
  relocate(MCI, .after = CFDDS)


# Make age groups of equal range
nhanes_homework <- nhanes_clean %>%
  mutate(age_groups = cut_interval(RIDAGEYR, n = 3)) %>%
  relocate(age_groups, .after = RIDAGEYR)
table(nhanes_homework$age_groups, nhanes_homework$race_eth)

nhanes_homework <- nhanes_homework %>%
  mutate(age_groups = relevel(factor(age_groups),
                            ref = "[60,66.7]"))

  #             Non-Hispanic White Mexican American Non-Hispanic Black Other Hispanic
  # [60,66.7]                  256              109                181             82
  # (66.7,73.3]                230               65                107             44
  # (73.3,80]                  410               36                100             28
  #            
  #             Other Race
  # [60,66.7]           89
  # (66.7,73.3]         60
  # (73.3,80]           44
```


# Save dataset

```{r}

# Save dataset as an R object
save(nhanes_homework, file = here("nhanes_homework.rda"))
```